/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "deep-teal": "#02090A",
        "background": "#141313",
        "on-tertiary-fixed": "#1a1c1c",
        "neon-green": "#36F4A4",
        "on-tertiary": "#2f3131",
        "secondary-fixed": "#4fffaf",
        "shade-60": "#52525B",
        "on-secondary-fixed-variant": "#005233",
        "on-primary-fixed-variant": "#454747",
        "outline": "#8e9192",
        "tertiary-fixed-dim": "#c6c6c7",
        "link-sage": "#9DABAD",
        "inverse-on-surface": "#313030",
        "surface-container-high": "#2a2a2a",
        "shade-30": "#D4D4D8",
        "tertiary": "#ffffff",
        "primary-fixed": "#e2e2e2",
        "on-error": "#690005",
        "on-surface": "#e5e2e1",
        "pistachio": "#D4F9E0",
        "muted-text": "#A1A1AA",
        "on-tertiary-fixed-variant": "#454747",
        "surface-dim": "#141313",
        "secondary-fixed-dim": "#05e294",
        "on-secondary-container": "#005f3b",
        "on-surface-variant": "#c4c7c8",
        "error": "#ffb4ab",
        "surface": "#141313",
        "primary": "#ffffff",
        "void": "#000000",
        "on-primary-container": "#636565",
        "primary-fixed-dim": "#c6c6c7",
        "tertiary-container": "#e2e2e2",
        "forest": "#102620",
        "surface-bright": "#3a3939",
        "inverse-surface": "#e5e2e1",
        "shade-50": "#71717A",
        "dark-forest": "#061A1C",
        "shade-70": "#3F3F46",
        "dark-border": "#1E2C31",
        "surface-container-lowest": "#0e0e0e",
        "inverse-primary": "#5d5f5f",
        "tertiary-fixed": "#e2e2e2",
        "on-background": "#e5e2e1",
        "secondary": "#4fffaf",
        "surface-tint": "#c6c6c7",
        "primary-container": "#e2e2e2",
        "on-primary-fixed": "#1a1c1c",
        "link-mint": "#99B3AD",
        "on-primary": "#2f3131",
        "on-secondary": "#003822",
        "aloe": "#C1FBD4",
        "on-secondary-fixed": "#002112",
        "on-tertiary-container": "#636565",
        "secondary-container": "#05e294",
        "error-container": "#93000a",
        "surface-container-highest": "#353434",
        "on-error-container": "#ffdad6",
        "surface-variant": "#353434",
        "surface-container": "#201f1f",
        "surface-container-low": "#1c1b1b",
        "outline-variant": "#444748"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "space-1": "4px",
        "space-2": "8px",
        "space-3": "12px",
        "space-4": "16px",
        "space-5": "24px",
        "space-6": "28px",
        "space-7": "32px",
        "space-8": "36px",
        "space-9": "40px",
        "space-10": "64px",
        "theatrical-gap": "120px",
      },
      fontFamily: {
        "display-xl": ["Plus Jakarta Sans", "sans-serif"],
        "code": ["monospace"],
        "heading-3": ["Plus Jakarta Sans", "sans-serif"],
        "body-large": ["Plus Jakarta Sans", "sans-serif"],
        "body-medium": ["Inter", "sans-serif"],
        "nav-link": ["Plus Jakarta Sans", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
        "display-light": ["Plus Jakarta Sans", "sans-serif"],
        "heading-4": ["Plus Jakarta Sans", "sans-serif"],
        "overline": ["Plus Jakarta Sans", "sans-serif"],
        "heading-2": ["Plus Jakarta Sans", "sans-serif"],
        "heading-1": ["Plus Jakarta Sans", "sans-serif"],
        "body-standard": ["Inter", "sans-serif"],
        "display-xl-bold": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "display-xl": ["96px", { lineHeight: "1.00", fontWeight: "400" }],
        "code": ["16px", { lineHeight: "1.50", fontWeight: "400" }],
        "heading-3": ["48px", { lineHeight: "1.14", fontWeight: "300" }],
        "body-large": ["20px", { lineHeight: "1.40", letterSpacing: "0.3px", fontWeight: "500" }],
        "body-medium": ["18px", { lineHeight: "1.56", fontWeight: "500" }],
        "nav-link": ["18px", { lineHeight: "1.25", letterSpacing: "0.72px", fontWeight: "500" }],
        "caption": ["14px", { lineHeight: "1.49", letterSpacing: "0.28px", fontWeight: "500" }],
        "display-light": ["96px", { lineHeight: "0.96", fontWeight: "300" }],
        "heading-4": ["32px", { lineHeight: "1.14", letterSpacing: "0.32px", fontWeight: "400" }],
        "overline": ["15.36px", { lineHeight: "1.50", letterSpacing: "1.54px", fontWeight: "400" }],
        "heading-2": ["55px", { lineHeight: "1.16", fontWeight: "300" }],
        "heading-1": ["70px", { lineHeight: "1.00", fontWeight: "300" }],
        "body-standard": ["18px", { lineHeight: "1.56", fontWeight: "400" }],
        "display-xl-bold": ["90.74px", { lineHeight: "1.00", letterSpacing: "4.54px", fontWeight: "700" }]
      },
      boxShadow: {
        'card': '0 4px 40px rgba(0,0,0,0.8)',
      },
      animation: {
        'fadeIn': 'fadeIn 0.5s ease-in-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: 0 },
          '100%': { opacity: 1 },
        },
      },
    },
  },
  plugins: [],
}
