server:
  port: 8081
spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ticket_service_db
    username: ticket_user
    password: ticket_password
    driver-class-name: org.postgresql.Driver

  jpa:
    # open-in-view: false (Best practice)
    # Tắt việc giữ connection tới view layer, giúp tăng hiệu năng cho DB
    open-in-view: false

    hibernate:
      # ddl-auto: update
      # Tự động so sánh Entity và DB:
      # - Nếu bảng chưa có -> Tự tạo.
      # - Nếu thiếu cột -> Tự thêm.
      # (Rất tiện cho giai đoạn code Khóa luận)
      ddl-auto: update

    # In câu SQL ra console để bạn debug xem Hibernate đang làm gì
    show-sql: true
    properties:
      hibernate:
        format_sql: true # Format câu SQL cho đẹp dễ nhìn
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Cấu hình logging để dễ nhìn lỗi
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # Xem giá trị tham số ? trong câu SQL