server:
  port: 8082

spring:
  application:
    name: payment-service

  datasource:
    # URL kết nối MySQL với schema payment_db
    # createDatabaseIfNotExist=true: Tự tạo DB nếu chưa có
    # useSSL=false: Tắt bảo mật SSL để đỡ lỗi certificate khi dev
    # allowPublicKeyRetrieval=true: Cho phép driver lấy public key từ server (Bắt buộc với MySQL 8.0+)
    url: jdbc:mysql://localhost:3306/payment_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: 3307a001
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    # Tắt open-in-view để tăng hiệu năng
    open-in-view: false
    hibernate:
      # ddl-auto: update - Tự động sync Entity với DB
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # Redis configuration cho Distributed Lock (chống duplicate webhook)
  data:
    redis:
      host: localhost
      port: 6379
      # password: your_redis_password  # Uncomment nếu Redis có password
      timeout: 6000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

# Logging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.spike.ticket: DEBUG

momo:
  payment-endpoint: https://test-payment.momo.vn/v2/gateway/api/create
  refund-endpoint: https://test-payment.momo.vn//v2/gateway/api/refund
  partner-code: MOMO
  access-key: F8BBA842ECF85
  secret-key: K951B6PE1waDMi640xX08PD3vg6EkVlz
  # URL chuyển hướng về Frontend sau khi khách thanh toán xong (Return URL)
  redirect-url: http://localhost:8082/api/v1/payments/momo-return
  # URL Webhook chạy ngầm server-to-server (ĐƯỜNG HẦM NGROK CỦA BẠN)
  ipn-url:   https://fidgetingly-intermeningeal-matha.ngrok-free.devapi/v1/payments/momo-ipn